<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sobre o Centro | SDQ</title>
    <link rel="shortcut icon" href="img/logo_p.png" type="image/x-icon">
    <link rel="stylesheet" href="estilo.css">
    <link rel="stylesheet" href="estilo.beneficios.css">
    <link rel="stylesheet" href="produto.css">
    <link rel="stylesheet" href="cursos.css">
    <script src="js/jquery.js"></script>
    <script src="aos/aos.js"></script>
    <link rel="stylesheet" href="aos/aos.css">
    <script src="js/jquery.min.js"></script>
    <link rel="stylesheet" href="alerts/sweetalert2.css">
    <script src="alerts/sweetalert2.js"></script>
    <script src="js/bootstrap.js"></script>
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FHBP9WB24G"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FHBP9WB24G');
</script>
</head>
<style>
    
    @font-face {
        font-family: euro;
        src: url(fontes/eurof75.ttf);
    }

    @font-face {
        font-family: euro2;
        src: url(fontes/eurof55.ttf);
    }

    @font-face {
        font-family: gokside;
        src: url(fontes/78936___.TTF);
    }
    
    @font-face {
        font-family: club;
        src: url(fontes/CLUB____.TTF);
    }
    
    @font-face {
        font-family: edoz;
        src: url(fontes/edosz.ttf);
    }
    

    .foot{
        position: relative!important;
        bottom: 0!important;
        left: 0!important;
        right: 0!important;
        padding: .5rem 0;
    }

    ul li{
      list-style-type: none;
    }

    h4{
        font-family: edoz;
        align-items: center;
    }


    
    ::-webkit-scrollbar{
        width: 15px!important;
        cursor: pointer!important;
    }

    ::-webkit-scrollbar-track{
        box-shadow: inset 0 0 5px grey!important;
        border-radius: 10px!important;
    }

    ::-webkit-scrollbar-thumb{
        background: #de0877!important;
        border-radius: 10px!important;
    }

    ::-webkit-scrollbar-thumb:hover{
        background: #f787c1!important;
    }


    body{
    font-family: gokside;
    }

    
    .foot{
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        padding: .5rem 0;
        text-align: center;
    }


    @media screen and (max-width: 800px) {
      .img{
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            height: 18vh;
            z-index: 10000;
        }

        .img img{
            height: 2em;
        }
        .corpo{
            margin-top: 19vh;
        }
    }

  .foo ul {
    list-style-type: none;
    margin-left: -1rem;
    margin-top: 1rem;
  }

  .foo ul li a{
    color: white;
  }

  body{
    overflow-x: hidden!important;
  }

</style>
<body>
    <div class="bg-s img shadow" >
        <!-- Generated by IcoMoon.io -->
    
    <a href="index.html">
         <svg class="m-3" version="1.1" fill="#de0877" xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 24 24">
        <title>Voltar</title>
        <path d="M23.312 11.25h-19.558l4.5-4.5-1.061-1.061-6.31 6.31 6.31 6.31 1.061-1.061-4.5-4.5h19.558v-1.5z"></path>
        </svg>
         </a>   
     <center><img src="img/logo_s.png" height="70em" style="margin-top: 3vh;" alt=""></center>
  
    </div>
<br>
<main class="corpo container">
    <div class="conteudoo">
        <p>
         <center data-aos="fade-down">  <h4 class="text-s"> CENTRO DE FORMAÇÃO “SE DEUS QUISER”</h4>    </center>
<span data-aos="zoom-out">
    
O centro de formação “Se Deus Quiser” foi aberto no ano de 2012, propriamente no dia 6 de Junho de 2012. 
Existimos no mercado acerca de 10 anos no momento, e temos a certeza absoluta que pela qualidade de trabalho que nós prestamos, vamos existir eternamente. Porque todos os dias temos visto o nosso crescimento. <br><br>
</span>
Actuamos em diversas áreas, na qual damos formação de:


<ul>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=culinaria"> CULINÁRIA</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg><a href="inscrever-se.php?c=past"> PASTELARIA</a> </li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=decoracao">DECORAÇÃO</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=contabilidade_g">CONTABILIDADE GERAL</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href = "inscrever-se.php?c=cab_pro"> CABELEIREIRO</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=inf_o"> INFORMÁTICA NA ÓPTICA DO UTILIZADOR</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=inf_i">INFORMÁTICA COM INTERNET</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=redes">REDES DE COMPUTADORES</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg>  <a href="inscrever-se.php?c=cctv">CCTV - MONTAGEM DE CAMARAS DE VIGILÂNCIA</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=hard_inf">HARDWARE & Software - Reparação De Computadores & Instalação De Programas</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=ped">PEDAGOGIA & DIDÁTICA</a></li>
      <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="#">Recepção, Secretariado, Antendimento ao Público</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=">SECRETARIADO</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=">RECEPÇÃO E ATENDIMENTO AO PÚBLICO</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=est_pro">ESTÉTICA</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=rh">GESTÃO DE RECURSOS HUMANOS</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=g_e">GESTÃO DE EMPRESAS</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=ed_i">EDUCAÇÃO INFANTIL </a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=ingles_a_b">INGLÊS</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=contabilidade_i">CONTABILIDADE INFORMATIZADA</a></li>
     <li data-aos="fade-right"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="#de0877" viewBox="0 0 24 24">
                  <title>incluido</title>
                  <path d="M9.331 21.375l-0.346-0.352-0.185-0.183-4.040-4.041 0.002-0.003-3.922-3.922 4.576-4.576 3.917 3.917 9.341-9.341 4.576 4.576-9.869 9.874zM6.872 16.79l2.459 2.459 0.005-0.005 0.003 0.003 2.452-2.452 0.528-0.533 8.811-8.811-2.454-2.454-9.341 9.341-3.917-3.917-2.454 2.454 3.912 3.912z"></path>
                  </svg> <a href="inscrever-se.php?c=excel_a">EXCEL AVANÇADO</a></li>
    <br>
    <li data-aos="fade-up">E tantos outros cursos, concorridos no mercado.</li>
</ul>
<br>

<p>
    
Nós surgimos, com o objectivo de encontrarmos um público-alvo muito sofredora ( <span class="text-s"> a juventude angolana</span>). 
A nossa missão é dar formação de qualidade, e para poder atender as espectativas da empresa. 
É assim que nós temos como visão chegar até as <span class="text-s"> 18 províncias</span> do país.
<br>
<br>
Temos três( 3 ) centros de formação nesse momento, e estamos abrindo outros centros também. Temos como valores: honestidade, sinceridade, dignidade.
O Centro de Formação “ <b class="text-s f-25" > Se Deus Quiser</b>” trabalha semestralmente, com uma média de <b class="text-s f-25" > 500 alunos</b> por Centro. <br><br>
Contudo, aconselhamos às pessoas que estiverem a procura de uma formação com qualidade, que cheguem até às nossas instalações.

</p>

        </p>
    </div>
</main>

<br>
<hr style="color: #de0877!important;">
<br>
<center><h4 class="text-s"><b>Entre em Contacto</b></h4></center><br>
<div class="container">
    <span>Tel: <a href="tel:+244938650523">+244 938 650 523</a></span><br>
    <span>Tel: <a href="tel:+244916043850">+244 916 043 850</a></span><br>
    <span>Email: <a href="mailto:sedeusquiser@gmail.com">geral@sedeusquiser.co.ao</a></span><br>
    <span>WebSite: <a href="http://sedeusquiser.org">www.sedeusquiser.org</a></span>
    <br><br>
    <div class="row container text-center">
        <div class="col-6 col-md-6 col-lg-6 col-sm-6 col-xs-6">
            <b class="text-s" data-aos="fade-right">INEFOP</b>
        </div>
        <div class="col-6 col-md-6 col-lg-6 col-sm-6 col-xs-6">
            <span class="text-s" data-aos="fade-up">MAPTESS</span>
        </div>
    </div>
</div>

<br><br>
<div class="bg-s2 foo">
  <div class="msg">
    <div class="container row">
      <div class="col-12 col-lg-8 col-md-9 col-sm-9 col-xs-9">
          <br>
          <h3 class="text-white my-4">
            Entrar em contacto
          </h3>  
          <div class="form-group">
            <input type="email" name="email" id="email_m" placeholder="Seu email" class="form-control">
            <br>
            <input type="tel" name="email" id="tel" placeholder="Nº de telefone" class="form-control">
            <br>
            <textarea placeholder="Escreva a sua mensagem" name="msg" id="msg_m" cols="30" rows="3" class="form-control"></textarea>
            <br>
            <button id="enviar_m" class="btn btn-large btn-outline-secondary w-100" style="color: white; border-color: white; ">Enviar</button>
          </div>
      </div>
      <div class="col-12 col-lg-4 col-md-3 col-sm-3 col-xs-3">
        
      </div>
    </div>
  </div>

  <div class="info">
    <div class="row">
      <div class="col-12 col-lg-4 col-md-4 col-sm-6 col-xs-4 my-4">
        <div class="container">
          <span class="blockquote-footer">Contactos</span>
          <div class="">
            <ul>
              <li><a href="tel:+244938650523">+244 938 650 523</a></li>
              <li><a href="tel:+244916043850">+244 916 043 850</a></li>
              <li><a href="#">www.sedeusquiser.net</a></li>
              <li><a href="mailto:sedeusquiser@gmail.com">geral@sedeusquiser.co.ao</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-4 col-md-4 col-sm-6 col-xs-4 my-4">
        <div class="container">
          <span class="blockquote-footer">GoKourses</span>
          <div class="">
            <ul>
              <li><a href="tel:+244938172276">+244 938 172 276</a></li>
              <li><a href="tel:+244946445629">+244 946 445 629</a></li>
              <li><a href="mailto:goncalvesgm10@gmail.com">goncalvesgm10@gmail.com</a></li>
              <li><a href="mailto:jkatumbela@gmail.com">jkatumbela9@gmail.com</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-4 col-md-4 col-sm-6 col-xs-4 my-4">
        <div class="container">
          <span class="blockquote-footer">Links rápidos</span>
          <div class="">
            <ul>
              <li><a href="#cursos">Cursos</a></li>
              <li><a href="asign.html">Pacotes</a></li>
              <li><a href="sobre.html">Sobre o centro</a></li>
              <li><a href="centros.html">Centros</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class=" bg-s3 py-3" style="margin-bottom: -1.5rem;"> 
    <center>
    <span class="text-muted">&copy; 2022 &middot; Se Deus Quiser</span><br>
   <span class="text-muted">Powered By <a href="http://gokourses.web.app/">GoKourses</a></span></center>
  </div>
  <br>
</div>



<script>
          AOS.init({
        easing: 'ease-in-out-sine'
      });

      

$('#enviar_m').click(function (e) {
  e.preventDefault;
  var email = $('#email_m').val();
  var msg = $('#msg_m').val();
  var tel = $('#tel').val();

  var dados = {
    email: email,
    msg: msg,
  }
  if (tel == "") {
    Swal.fire(
        'Ops!',
        'Por favor indique seu telefone e escreva alguma mensagem!',
        'error'
      );
  }
  else {

  $.post('php/msg.php', dados, function (retorno, suc) {
    if (suc = "success") {
      Swal.fire(
        'Obrigado pelo seu contacto',
        'Sua mensagem foi cadastrada com sucesso',
        'success'
      );

        $('#email_m').val("");
        $('#msg_m').val("");
        $('#tel').val("");

    }
  });

} //termino do else

});

      
</script>
</body>
</html>